// <auto-generated />
namespace SG_ASP_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addauditoria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addauditoria));
        
        string IMigrationMetadata.Id
        {
            get { return "202105102156293_addauditoria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
